datasets:
  ocr_coco:
    data_type: images
    build_info:
      json_path: /hetu_group/wangyan/datasets/coco/coco_text_after_process.json
      vis_root: /hetu_group/wangyan/datasets/coco/train2014/