datasets:
  ocr_art:
    data_type: images
    build_info:
      json_path: /hetu_group/wangyan/datasets/ocr_art/train_images_after_process2.json
      vis_root: /hetu_group/wangyan/datasets/ocr_art/train_images